tasks:
    - task: niah
      metric: all
      filenames:
          - niah_single_2.jsonl
          - niah_multikey_1.jsonl
          - niah_multikey_2.jsonl
          - niah_multikey_3.jsonl

    - task: qa
      metric: part
      filenames:
          - squad.jsonl
          - jsquad.jsonl
          - hotpotqa.jsonl
          - jemhopqa.jsonl
