download_datasource: true
hf_dataset_configs:
    jsquad:
        output_filepath: datasets/benchmarks/ruler/raw/japanese/qa/jsquad.jsonl
        huggingface_dataset_name: sbintuitions/JSQuAD
        split: validation

    jemhopqa:
        output_filepath: datasets/benchmarks/ruler/raw/japanese/qa/jemhopqa.jsonl
        huggingface_dataset_name: sbintuitions/JEMHopQA
        name: v1.2-extended-answers
        split: validation

url_dataset_configs:
    squad:
        output_filepath: datasets/benchmarks/ruler/raw/english/qa/squad.json
        dataset_url: https://rajpurkar.github.io/SQuAD-explorer/dataset/dev-v2.0.json
    hotpotqa:
        output_filepath: datasets/benchmarks/ruler/raw/english/qa/hotpotqa.json
        dataset_url: http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_dev_distractor_v1.json

essay_dataset_config:
    output_filepath: datasets/benchmarks/ruler/raw/english/niah/PaulGrahamEssays.json
    url_list_path: scripts/benchmarks/RULER/download_evaluation_dataset/paulgraham_essay_urls.txt
