output_root: outputs/benchmarks
dataset_root: datasets/benchmarks
batchsize: 1

run_name: null
llm: null

wandb:
    null
    # entity: xxx
    # project: longcontext_evaluation_benchmark

benchmarks:
    longbench_v2:
        longbench_v2_eng:
            all:
                language: english
                dataset_filename: english/longbench_v2_with_token_count.jsonl
                inference_mode: chat
                metric: all
                settings:
                    use_truncate: true
                    rag_topn: 0
                    cot: false
                    no_context: false
                    compensate_missing: false
                    prompt:
                        dirpath: scripts/benchmarks/LongBench_v2/prompts
                        files:
                            zero_shot: 0shot.txt
                            zero_shot_cot: 0shot_cot.txt
                            zero_shot_cot_ans: 0shot_cot_ans.txt
                            zero_shot_no_context: 0shot_no_context.txt
                            zero_shot_rag: 0shot_rag.txt
