output_dir: ~/longcontext-llm-benchmark-eval/experimentation/outputs
dataset_dir: ~/datasets
batchsize: 1

benchmarks:
  longbench_v2:
    enabled: true
    tasks:
      prompt:
        dirpath: ../LongBench_v2/prompts
        prompts:
          0shot: 0shot.txt
          0shot_cot: 0shot_cot.txt
          0shot_cot_ans: 0shot_cot_ans.txt
          0shot_no_context: 0shot_no_context.txt
          0shot_rag: 0shot_rag.txt
    run_pred: true
    run_eval: true
    rag_topn: 0
    cot: false
    no_context: false
    compensate_missing: false
    wandb: {}

  mrcr:
    enabled: true
    tasks:
      tasks:
        mrcr:
          - 2needle.parquet
          - 4needle.parquet
          - 8needle.parquet
        mrcr_jpn:
          - 2needle.parquet
          - 4needle.parquet
          - 8needle.parquet
    eval_config:
      tasks:
        - task: mrcr
          metric: all
          filenames:
            - 2needle.parquet
            - 4needle.parquet
            - 8needle.parquet
        - task: mrcr_jpn
          metric: all
          filenames:
            - 2needle.parquet
            - 4needle.parquet
            - 8needle.parquet
    run_pred: true
    run_eval: true
    wandb: {}

  ruler:
    enabled: true
    tasks:
      tasks:
        niah:
          - niah_single_2.jsonl
          - niah_multikey_1.jsonl
          - niah_multikey_2.jsonl
          - niah_multikey_3.jsonl
        qa:
          - squad.jsonl
          - hotpotqa.jsonl
          - jsquad.jsonl
          - jemhopqa.jsonl
    eval_config:
      tasks:
        - task: niah
          metric: all
          filenames:
            - niah_single_2.jsonl
            - niah_multikey_1.jsonl
            - niah_multikey_2.jsonl
            - niah_multikey_3.jsonl

        - task: qa
          metric: part
          filenames:
            - squad.jsonl
            - jsquad.jsonl
            - hotpotqa.jsonl
            - jemhopqa.jsonl
    run_pred: true
    run_eval: true
    wandb: {}
