output_root: outputs/benchmarks
dataset_root: datasets/benchmarks
batchsize: 1

llm: null

wandb:
    entity: xxx
    project: xxx
    id: xxx
    name: xxx

benchmarks:
  longbench_v2:
        longbench_v2_eng:
            all:
                language: english
                dataset_filename: english/longbench_v2_with_token_count.jsonl
                metric: all
                settings:
                    rag_topn: 0
                    cot: false
                    no_context: false
                    compensate_missing: false
                    prompt:
                        dirpath: scripts/benchmarks/LongBench_v2/prompts
                        prompts:
                            0shot: 0shot.txt
                            0shot_cot: 0shot_cot.txt
                            0shot_cot_ans: 0shot_cot_ans.txt
                            0shot_no_context: 0shot_no_context.txt
                            0shot_rag: 0shot_rag.txt

  openai_mrcr:
        mrcr_eng:
            2needle:
                language: english
                dataset_filename: english/2needle.parquet
                metric: all
            4needle:
                language: english
                dataset_filename: english/4needle.parquet
                metric: all
            8needle:
                language: english
                dataset_filename: english/8needle.parquet
                metric: all
        mrcr_jpn:
            2needle:
                language: japanese
                dataset_filename: japanese/2needle.parquet
                metric: all
            4needle:
                language: japanese
                dataset_filename: japanese/4needle.parquet
                metric: all
            8needle:
                language: japanese
                dataset_filename: japanese/8needle.parquet
                metric: all

  ruler:
        niah:
            niah_single_2:
                language: english
                dataset_filename: niah/niah_single_2.jsonl
                metric: all
            niah_multikey_1:
                language: english
                dataset_filename: niah/niah_multikey_1.jsonl
                metric: all
            niah_multikey_2:
                language: english
                dataset_filename: niah/niah_multikey_2.jsonl
                metric: all
            niah_multikey_3:
                language: english
                dataset_filename: niah/niah_multikey_3.jsonl
                metric: all
        qa:
            squad:
                language: english
                dataset_filename: qa/squad.jsonl
                metric: part
            hotpotqa:
                language: english
                dataset_filename: qa/hotpotqa.jsonl
                metric: part
            jsquad:
                language: japanese
                dataset_filename: qa/jsquad.jsonl
                metric: part
            jemhopqa:
                language: japanese
                dataset_filename: qa/jemhopqa.jsonl
                metric: part
